version: 2.1

executors:
  ubuntu-executor:
    docker:
      - image: cimg/base:current-20.04

orbs:
  terraform: circleci/terraform@3.0.0

commands:
  set_pull_request_branch:
    steps:
      - run:
          name: Getting target branch
          command: |
            # Default branch to avoid issues.
            target_branch="master"
            echo "export LG_PR_TARGET=$target_branch" >> "$BASH_ENV"
jobs:

  validate:
    executor: ubuntu-executor
    steps:
      # Install Terraform
      - run:
          name: Install Terraform
          command: |
            TERRAFORM_VERSION="1.3.4"  # Replace with the desired Terraform version
            curl -LO "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            unzip "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            sudo mv terraform /usr/local/bin/
            rm "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"

      # Configure AWS credentials
      - run:
          name: Configure AWS credentials
          command: |
            echo 'export AWS_ACCESS_KEY_ID=AKIART3KNLOLR4AWBXLW' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=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' >> $BASH_ENV
            source $BASH_ENV
      - checkout
      - set_pull_request_branch
      - run:
          name: "Initialize resources"
          command: ./scripts/terraform init
      - persist_to_workspace:
          root: .
          paths:
            - .terraform
            - .terraform.lock.hcl
            - environments
            - modules
            - scripts
            - shared
            - tfstates

  plan:
    executor: ubuntu-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Terraform
          command: |
            TERRAFORM_VERSION="1.3.4"  # Replace with the desired Terraform version
            curl -LO "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            unzip "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            sudo mv terraform /usr/local/bin/
            rm "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"

      # Configure AWS credentials
      - run:
          name: Configure AWS credentials
          command: |
            echo 'export AWS_ACCESS_KEY_ID=AKIART3KNLOLR4AWBXLW' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=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' >> $BASH_ENV
            source $BASH_ENV
      - set_pull_request_branch
      - run:
          name: "Plan changes"
          command: ./scripts/terraform plan
      - persist_to_workspace:
          root: .
          paths:
            - environments/*/tfplan

  apply:
    executor: ubuntu-executor
    steps:
      - attach_workspace:
          at: .
      - set_pull_request_branch
      - run:
          name: Install Terraform
          command: |
            TERRAFORM_VERSION="1.3.4"  # Replace with the desired Terraform version
            curl -LO "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            unzip "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            sudo mv terraform /usr/local/bin/
            rm "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"

      # Configure AWS credentials
      - run:
          name: Configure AWS credentials
          command: |
            echo 'export AWS_ACCESS_KEY_ID=AKIART3KNLOLR4AWBXLW' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=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' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: verifying1
          command: ls /home/circleci/project/environments/root/lambdas_code/dms_stop_tasks

      - run:
          name: verifying2
          command: ls 

      - run:
          name: "Apply changes"
          command: scripts/terraform apply && ls /home/circleci/project/environments/root/lambdas_code/dms_stop_tasks && ls 

workflows:
  validate_and_plan:
    jobs:
      - validate
      - plan:
          requires:
            - validate
      - apply:
          requires:
            - plan

#   build:
#     executor: ubuntu-executor

#     steps:
#       - checkout

#       # Install Terraform
#       - run:
#           name: Install Terraform
#           command: |
#             TERRAFORM_VERSION="1.0.0"  # Replace with the desired Terraform version
#             curl -LO "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
#             unzip "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
#             sudo mv terraform /usr/local/bin/
#             rm "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"

#       # Configure AWS credentials
#       - run:
#           name: Configure AWS credentials
#           command: |
#             echo 'export AWS_ACCESS_KEY_ID=AKIART3KNLOLR4AWBXLW' >> $BASH_ENV
#             echo 'export AWS_SECRET_ACCESS_KEY=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' >> $BASH_ENV
#             source $BASH_ENV

#       # Install Terraform dependencies
#       - run:
#           name: Install Terraform dependencies
#           command: |
#             terraform init

#       # Validate Terraform configuration
#       - run:
#           name: Validate Terraform configuration
#           command: |
#             terraform validate

#       # Plan and apply Terraform changes
#       - run:
#           name: Plan and apply Terraform changes
#           command: |
#             terraform plan -out=tfplan

#       - run:
#           name: Apply Terraform changes
#           command: |
#             terraform apply tfplan

#       - run:
#           name: verifying
#           command: unzip lambdas_code/dms_stop_tasks/code.zip

#       - run:
#           name: verifying2
#           command: ls lambdas_code/dms_stop_tasks

#       - run:
#           name: verifying3
#           command: ls lambdas_code/dms_stop_tasks/code
# workflows:
#   build:
#     jobs:
#       - build
