version: 2.1

executors:
  ubuntu-executor:
    docker:
      - image: cimg/base:current-20.04
jobs:
  build:
    executor: ubuntu-executor

    steps:
      - checkout

      # Install Terraform
      - run:
          name: Install Terraform
          command: |
            TERRAFORM_VERSION="1.0.0"  # Replace with the desired Terraform version
            curl -LO "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            unzip "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            sudo mv terraform /usr/local/bin/
            rm "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"

      # Configure AWS credentials
      - run:
          name: Configure AWS credentials
          command: |
            echo 'export AWS_ACCESS_KEY_ID=AKIART3KNLOLR4AWBXLW' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=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' >> $BASH_ENV
            source $BASH_ENV

      # Install Terraform dependencies
      - run:
          name: Install Terraform dependencies
          command: |
            terraform init

      # Validate Terraform configuration
      - run:
          name: Validate Terraform configuration
          command: |
            terraform validate

      - run:
          name: Generate Lambda code ZIP
          command: terraform apply -target=data.archive_file.lambda_code && ls /home/circleci/project/lambdas_code/dms_stop_tasks && pwd

      - run:
          name: Generate Lambda code ZIP2
          command: terraform apply -target=data.archive_file.lambda_code && ls /home/circleci/project/lambdas_code/dms_stop_tasks && ls /lambdas_code/dms_stop_tasks/

      - run:
          name: Generate Lambda code ZIP2
          command: terraform apply -target=data.archive_file.lambda_code && ls /home/circleci/project/lambdas_code/dms_stop_tasks && ls lambdas_code/dms_stop_tasks/

      # Plan and apply Terraform changes
      - run:
          name: Plan and apply Terraform changes
          command: |
            terraform plan -out=tfplan
            terraform apply tfplan

workflows:
  build:
    jobs:
      - build
