version: 2.1

executors:
  ubuntu-executor:
    docker:
      - image: cimg/base:current-20.04

orbs:
  terraform: circleci/terraform@3.0.0
  slack: circleci/slack@4.3.0

commands:
  set_pull_request_branch:
    steps:
      - run:
          name: Getting target branch
          command: |
            # Default branch to avoid issues.
            target_branch="master"
            echo "export LG_PR_TARGET=$target_branch" >> "$BASH_ENV"
  notify_slack_error:
    steps:
      - slack/notify:
          branch_pattern: "master|staging|production"
          event: fail
          channel: $SLACK_CHANNEL
          template: basic_fail_1

  notify_slack_pass:
    steps:
      - run:
          name: Print Commit Message
          command: |
            echo 'export COMMIT_MESSAGE=$(git log --format=%B -n 1 $CIRCLE_SHA1)' >> $BASH_ENV
            echo 'export BLOCK_KIT=$(cat .circleci/templates/basic_success.json)' >> $BASH_ENV
            source $BASH_ENV


      - run:
          name: Print2 Commit Message
          command: cat .circleci/templates/basic_success.json

      - run:
          name: Print2 Commit Message
          command: |
            echo $COMMIT_MESSAGE

      - run:
          name: Print3 BLOCK Message
          command: |
            echo $BLOCK_KIT

      - slack/notify:
          branch_pattern: "master|staging|production"
          event: pass
          channel: $SLACK_CHANNEL
          custom: |
              $BLOCK_KIT
          # custom: !!str |-
          #   $(cat .circleci/templates/basic_succes.json)


          # custom: $BLOCK_KIT
          # custom: |
          #   {
          #     "blocks": [
          #       {
          #         "type": "header",
          #         "text": {
          #           "type": "plain_text",
          #           "text": "Job Succeeded. :white_check_mark:",
          #           "emoji": true
          #         }
          #       },
          #       {
          #         "type": "section",
          #         "fields": [
          #           {
          #             "type": "mrkdwn",
          #             "text": "*Job*: ${CIRCLE_JOB}"
          #           }
          #         ]
          #       },
          #       {
          #         "type": "section",
          #         "fields": [
          #           {
          #             "type": "mrkdwn",
          #             "text": "*Project*: $CIRCLE_PROJECT_REPONAME"
          #           },
          #           {
          #             "type": "mrkdwn",
          #             "text": "*Branch*: $CIRCLE_BRANCH"
          #           },
          #           {
          #             "type": "mrkdwn",
          #             "text": "*Commit*: $CIRCLE_SHA1"
          #           },
          #           {
          #             "type": "mrkdwn",
          #             "text": "*Commit Message*: $COMMIT_MESSAGE"
          #           },
          #           {
          #             "type": "mrkdwn",
          #             "text": "*Author*: $CIRCLE_USERNAME"
          #           }
          #         ],
          #         "accessory": {
          #           "type": "image",
          #           "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
          #           "alt_text": "CircleCI logo"
          #         }
          #       },
          #       {
          #         "type": "section",
          #         "fields": [
          #           {
          #             "type": "mrkdwn",
          #             "text": "*Mentions*: $SLACK_PARAM_MENTIONS"
          #           }
          #         ]
          #       },
          #       {
          #         "type": "actions",
          #         "elements": [
          #           {
          #             "type": "button",
          #             "action_id": "basic_success_view",
          #             "text": {
          #               "type": "plain_text",
          #               "text": "View Job"
          #             }
          #           }
          #         ]
          #       }
          #     ]
          #   }

jobs:

  validate:
    executor: ubuntu-executor
    steps:
      # # Install Terraform
      # - run:
      #     name: Install Terraform
      #     command: |
      #       TERRAFORM_VERSION="1.3.4"  # Replace with the desired Terraform version
      #       curl -LO "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
      #       unzip "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
      #       sudo mv terraform /usr/local/bin/
      #       rm "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"

      # # Configure AWS credentials
      # - run:
      #     name: Configure AWS credentials
      #     command: |
      #       echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID' >> $BASH_ENV
      #       echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY' >> $BASH_ENV
      #       source $BASH_ENV
      # - checkout
      # - set_pull_request_branch
      # - run:
      #     name: "Initialize resources"
      #     command: ./scripts/terraform init
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - .terraform
      #       - .terraform.lock.hcl
      #       - environments
      #       - modules
      #       - scripts
      #       - shared
      #       - tfstates
      - checkout
      - notify_slack_error
      - notify_slack_pass

  plan:
    executor: ubuntu-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Terraform
          command: |
            TERRAFORM_VERSION="1.3.4"  # Replace with the desired Terraform version
            curl -LO "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            unzip "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            sudo mv terraform /usr/local/bin/
            rm "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"

      # Configure AWS credentials
      - run:
          name: Configure AWS credentials
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY' >> $BASH_ENV
            source $BASH_ENV
      - set_pull_request_branch
      - run:
          name: "Plan changes"
          command: ./scripts/terraform plan

      - run:
          name: verifying2
          command: ls /home/circleci/project/environments/root/lambdas_code/dms_stop_tasks

      - persist_to_workspace:
          root: .
          paths:
            - environments/*/tfplan
            - environments/*/lambdas_code/*
            - environments/*/lambdas_test/*

  apply:
    executor: ubuntu-executor
    steps:
      - attach_workspace:
          at: .
      - set_pull_request_branch
      - run:
          name: Install Terraform
          command: |
            TERRAFORM_VERSION="1.3.4"  # Replace with the desired Terraform version
            curl -LO "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            unzip "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            sudo mv terraform /usr/local/bin/
            rm "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"

      # Configure AWS credentials
      - run:
          name: Configure AWS credentials
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: verifying2
          command: ls /home/circleci/project/environments/root/lambdas_code/dms_stop_tasks

      - run:
          name: "Apply changes"
          command: scripts/terraform apply  

  destroy:
    executor: ubuntu-executor
    steps:
      - attach_workspace:
          at: .
      - set_pull_request_branch
      - run:
          name: Install Terraform
          command: |
            TERRAFORM_VERSION="1.3.4"  # Replace with the desired Terraform version
            curl -LO "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            unzip "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            sudo mv terraform /usr/local/bin/
            rm "terraform_${TERRAFORM_VERSION}_linux_amd64.zip"

      # Configure AWS credentials
      - run:
          name: Configure AWS credentials
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: "destroy changes"
          command: scripts/terraform destroy  


workflows:
  validate_and_plan:
    jobs:
      - validate
      # - plan:
      #     requires:
      #       - validate
      # - apply:
      #     requires:
      #       - plan
      # - destroy:
      #     requires:
      #       - apply
