#  Terraform state for S3 backend config variables
region   = "us-east-1"
bucket   = "terraform-test1-tux"
key      = "terraform/test1"
encrypt  = "true"
dynamodb_table  = "terraform-test1-tux-table"
