#  Terraform state for S3 backend config variables
region   = "us-east-1"
bucket   = "terraform-test1-tux"
key      = "terraform/test1"
role_arn = "arn:aws:iam::881422822893:role/infrastructure-automation-role"
encrypt  = "true"
dynamodb_table  = "terraform-test1-tux-table"
